repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3.8
