---
    - hosts: prod
      tasks:
      
      - name: Remove docker-compose.yml 
        shell: |
          rm /home/{{ lookup('env','USER') }}/Media-API/docker-compose.yml
      
      - name: Copy docker-compose.yml
        copy:
          src: media_docker_compose.yml
          dest: /home/{{ lookup('env','USER') }}/Media-API/docker-compose.yml
      
      - name: Run docker container
        shell: |
          cd /home/{{ lookup('env','USER') }}/Media-API/
          docker-compose up --build -d
      