---
    - hosts: prod
      tasks:
      - name: Remove the nginx default 
        shell: |
          rm /etc/nginx/sites-available/default
        become: yes
        ignore_errors: yes
        
      - name: Copy nginx config file
        copy:
          src: default
          dest: /etc/nginx/sites-available/default
        become: yes
      
      - name: Copy django nginx config file
        copy:
          src: django_nginx
          dest: /etc/nginx/sites-available/{{ lookup('env','DJANGO_API_DOMAIN') }}
        become: yes
      
      - name: Enable django site
        shell: |
          ln -s /etc/nginx/sites-available/{{ lookup('env','DJANGO_API_DOMAIN') }} /etc/nginx/sites-enabled/{{ lookup('env','DJANGO_API_DOMAIN') }}
        become: yes
      
      - name: Copy mediaAPI nginx config file
        copy:
          src: media_nginx
          dest: /etc/nginx/sites-available/{{ lookup('env','MEDIA_API_DOMAIN') }}
        become: yes
      
      - name: Enable mediaAPI site
        shell: |
          ln -s /etc/nginx/sites-available/{{ lookup('env','MEDIA_API_DOMAIN') }} /etc/nginx/sites-enabled/{{ lookup('env','MEDIA_API_DOMAIN') }}
        become: yes
      
      - name: Reload nginx
        shell: |
          systemctl restart nginx
        become: yes